#![cfg(target_os = "linux")]

use std::net::TcpListener;
use std::os::unix::net::UnixListener;
use std::path::Path;
use std::time::{Duration, Instant};

use minimax_core::ToolSandboxPolicy;
use minimax_protocol::{ToolCall, ToolCallId, ToolEffect, ToolInvocation, ToolTerminalStatus};
use minimax_tools::{NeverCancelled, RunDiagnosticTool, WorkspaceRoot};
use serde_json::json;

#[tokio::test]
async fn transitive_build_code_is_isolated_in_confirm_and_explicitly_unrestricted_in_full_access() {
    assert!(
        Path::new("/usr/bin/bwrap").is_file() || Path::new("/bin/bwrap").is_file(),
        "Bubblewrap is a required Linux security-test dependency"
    );
    let host = tempfile::tempdir().expect("host fixture");
    let workspace_dir = tempfile::tempdir().expect("workspace");
    let marker = host.path().join("host-private-marker.txt");
    std::fs::write(&marker, "host-private").expect("host marker");

    let listener = TcpListener::bind("127.0.0.1:0").expect("host listener");
    listener
        .set_nonblocking(true)
        .expect("nonblocking listener");
    let port = listener.local_addr().expect("listener address").port();
    let unix_socket = workspace_dir.path().join("host-control.sock");
    let unix_listener = UnixListener::bind(&unix_socket).expect("host Unix listener");
    unix_listener
        .set_nonblocking(true)
        .expect("nonblocking Unix listener");
    write_malicious_cargo_fixture(workspace_dir.path(), &marker, port);
    let workspace = WorkspaceRoot::new(workspace_dir.path()).expect("workspace root");
    let tool = RunDiagnosticTool::production();
    let invocation = diagnostic_invocation();

    let restricted = tool
        .execute_with_policy(
            &workspace,
            &invocation,
            ToolSandboxPolicy::Restricted,
            &NeverCancelled,
        )
        .await;
    assert_eq!(
        restricted.status,
        ToolTerminalStatus::Succeeded,
        "{restricted:?}"
    );
    assert_canary(workspace_dir.path(), false, false, false);
    assert_no_connection(&listener, Duration::from_millis(250));
    assert_no_unix_connection(&unix_listener, Duration::from_millis(250));

    std::fs::remove_dir_all(workspace_dir.path().join("target")).expect("clear build cache");
    std::fs::remove_file(workspace_dir.path().join("sandbox-result.txt")).expect("clear result");
    let direct = tool
        .execute_with_policy(
            &workspace,
            &invocation,
            ToolSandboxPolicy::Disabled,
            &NeverCancelled,
        )
        .await;
    assert_eq!(direct.status, ToolTerminalStatus::Succeeded, "{direct:?}");
    assert_canary(workspace_dir.path(), true, true, true);
    assert_connection(&listener, Duration::from_secs(2));
    assert_unix_connection(&unix_listener, Duration::from_secs(2));
}

fn write_malicious_cargo_fixture(workspace: &Path, marker: &Path, port: u16) {
    std::fs::create_dir(workspace.join("src")).expect("source directory");
    std::fs::write(
        workspace.join("Cargo.toml"),
        "[package]\nname = \"sandbox-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\nbuild = \"build.rs\"\n",
    )
    .expect("manifest");
    std::fs::write(
        workspace.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"sandbox-fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("lockfile");
    std::fs::write(
        workspace.join("src/lib.rs"),
        "pub fn answer() -> u8 { 42 }\n",
    )
    .expect("library");
    let marker_literal = format!("{:?}", marker.to_string_lossy());
    let build_script = format!(
        r#"
use std::net::{{SocketAddr, TcpStream}};
use std::os::unix::net::UnixStream;
use std::time::Duration;

fn main() {{
    let host_file_read = std::fs::read_to_string({marker_literal}).is_ok();
    let address = SocketAddr::from(([127, 0, 0, 1], {port}));
    let network_connected = TcpStream::connect_timeout(&address, Duration::from_millis(200)).is_ok();
    let workspace = std::env::var_os("CARGO_MANIFEST_DIR").expect("manifest directory");
    let unix_socket = std::path::Path::new(&workspace).join("host-control.sock");
    let unix_socket_connected = UnixStream::connect(unix_socket).is_ok();
    let result = std::path::Path::new(&workspace).join("sandbox-result.txt");
    std::fs::write(
        result,
        format!("host_file_read={{host_file_read}}\nnetwork_connected={{network_connected}}\nunix_socket_connected={{unix_socket_connected}}\n"),
    ).expect("workspace write");
}}
"#
    );
    std::fs::write(workspace.join("build.rs"), build_script).expect("build script");
}

fn diagnostic_invocation() -> ToolInvocation {
    let call = ToolCall::new(
        ToolCallId::new("sandbox-adversarial").expect("call id"),
        "run_diagnostic",
        serde_json::to_string(&json!({"action": "cargo_test"})).expect("arguments"),
    )
    .expect("tool call");
    ToolInvocation::new(call, ToolEffect::Process).expect("invocation")
}

fn assert_canary(
    workspace: &Path,
    host_file_read: bool,
    network_connected: bool,
    unix_socket_connected: bool,
) {
    let result = std::fs::read_to_string(workspace.join("sandbox-result.txt"))
        .expect("workspace canary result");
    assert!(
        result.contains(&format!("host_file_read={host_file_read}")),
        "{result}"
    );
    assert!(
        result.contains(&format!("network_connected={network_connected}")),
        "{result}"
    );
    assert!(
        result.contains(&format!("unix_socket_connected={unix_socket_connected}")),
        "{result}"
    );
}

fn assert_no_connection(listener: &TcpListener, duration: Duration) {
    let deadline = Instant::now() + duration;
    while Instant::now() < deadline {
        match listener.accept() {
            Ok(_) => panic!("restricted child reached the host listener"),
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(10));
            }
            Err(error) => panic!("listener failed: {error}"),
        }
    }
}

fn assert_connection(listener: &TcpListener, duration: Duration) {
    let deadline = Instant::now() + duration;
    while Instant::now() < deadline {
        match listener.accept() {
            Ok(_) => return,
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(10));
            }
            Err(error) => panic!("listener failed: {error}"),
        }
    }
    panic!("full-access child did not reach the host listener");
}

fn assert_no_unix_connection(listener: &UnixListener, duration: Duration) {
    let deadline = Instant::now() + duration;
    while Instant::now() < deadline {
        match listener.accept() {
            Ok(_) => panic!("restricted child reached the host Unix listener"),
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(10));
            }
            Err(error) => panic!("Unix listener failed: {error}"),
        }
    }
}

fn assert_unix_connection(listener: &UnixListener, duration: Duration) {
    let deadline = Instant::now() + duration;
    while Instant::now() < deadline {
        match listener.accept() {
            Ok(_) => return,
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(10));
            }
            Err(error) => panic!("Unix listener failed: {error}"),
        }
    }
    panic!("full-access child did not reach the host Unix listener");
}
